// import localFont from "next/font/local";
// // import "./globals.css";
// import Footer from "./components/Footer";
// import Header from "./components/Header";

import Chatbot from "../Chatbot/page";
export const metadata = {
    title: "Travelling Postman",
    description: "Generated by create next app",
  };
  export default function AdminPerformanceDashboard({ children }) {
    return (
      <html lang="en">
        <body>
        <Chatbot > {children}</Chatbot>
        {/* {children} */}
        </body>
      </html>
    );
  }
  